CREATE USER 'dayzserver'@'%1' IDENTIFIED BY '20hng-1erthdayz243';
GRANT SELECT ON `dayzunleashed`.`squad_rank_name` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`squad_rank` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`squad` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`server_ip` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`server_instance` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`quest` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`player_login` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`player_data` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`object_spawns` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`object_data` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`object_classes` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`message` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`instance_state` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`instance_squad` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`instance_garage` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`instance_building` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`global_state` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`cust_loadout_profile` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`cust_loadout` TO 'dayzserver'@'%1';
GRANT SELECT, INSERT, UPDATE, DELETE ON `dayzunleashed`.`character_data` TO 'dayzserver'@'%1';
GRANT SELECT ON `dayzunleashed`.`building` TO 'dayzserver'@'%1';
GRANT INSERT ON `dayzunleashed`.`unleashed_instance_movement` TO 'dayzserver'@'%1';